name: go-main
on:
  push:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: "1.20.4"
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: "v1.52"
    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
      with:
        coverageCommand: go test -race -coverprofile c.out -covermode=atomic -v -bench=. ./...
        prefix: github.com/apito-cms/wsgraphql
        coverageLocations: ${{github.workspace}}/c.out:gocov
